### ISSUE TITLE
dont know where the feature request tab is so posting here sorry

### ISSUE THREAD

**Issue by Secretkeeper626** [Direwolf20-MC/DireGoo2#1]
is it possible for when the goo to replicate, it spreads in the direction of the nearest player?

**Comment by Direwolf20-MC** [comment]
Its probably possible to do this, but I worry that it would add even more processing for the goo to have to do on spread, which is already a rather 'expensive' (TPS wise) process. I'll consider it for a future feature update, but for now going to close the suggestion :). 

Thanks for the idea though!
