### ISSUE TITLE
Uses for the Goo

### ISSUE THREAD

**Issue by EmmaTheMartian** [Direwolf20-MC/DireGoo2#2]
The Goo currently seems more leaned to not having any uses (Maybe it does and I just missed it), so I think there should be some sort of items or blocks that require Goo to craft, or just a way of using Goo to help get rid of the Goo, like a "Goo Generator" that will use the Goo and turn it into RF/FE.
Edit: I would have given this a label, but I could not find out how....

**Comment by Direwolf20-MC** [comment]
Right now the goo is used for creating most of the defensive items/blocks in the game. It can also be used to speed up turrets. :)
